### ISSUE TITLE
can you share the results of your experiments

### ISSUE THREAD

**Issue by ghost** [nczempin/gym-tic-tac-toe#3]

**Comment by nczempin** [comment]
I'm not a researcher, not sure what experiments you're talking about.

**Comment by ghost** [comment]
You have written in repo readme that you intended to studh self play. I was
interested in knowing of you noticed anything interesting

**Comment by nczempin** [comment]
No, not really. It's not finished I would say.

These sorts of projects are sometimes what I do when I find myself with
some spare time on my hands, and then my full-time work kicks in again and
they're no longer a priority.

What I did find at the time was that OpenAI Gym was a little unwieldy at
the time (not sure if things have improved since then). The effort required
to wade through it, with it just being a little "indulge my curiosity"
project rather than actual research, probably played a part in the decision
not to pursue it further until the subject percolates to the top of my todo
list once more.

Do feel free to play with the code and provide feedback, though.

BTW an issue on GitHub is a report that something needs improvement, either
there should be some feature added or a bug needs to be fixed.

So unless you change the focus of this issue to reflect either, I will
close the issue.

Feel free though to simply send me an email through GitHub, or to send pull
requests for the code.
